Mark couple of font method as main actor
thumbtack/thumbprint-ios pull request #175
Opened 2024-10-16 20:46 UTC by Muhieddine-El-Kaissi

2024-10-16 23:27 UTC, scottasoutherland requested changes
I suspect you'd have problems trying to integrate this into our codebase as is. I'm guessing most of it would work, but i'm sure we have cases that fetch this font without being part of the mainactor. This is part of the reason i intend to move this over into the main iOS codebase, so we can test it out internally as we work on it without having to mess around with the package definitions. (tentatively planning this for next week).

2024-10-17 00:31 UTC, Muhieddine-El-Kaissi commented on Sources/Thumbprint/Font.swift
> +    @MainActor public static var traitCollectionOverrideForTesting: UITraitCollection?
i mark traitCollectionOverrideForTesting `nonisolated(unsafe)` as suggested. i kept the tests marked as mainactor as we need to do so anyway

2024-10-17 01:17 UTC, scottasoutherland commented on Sources/Thumbprint/Font.swift
> +    #if DEBUG
2 things. 

1. After thinking about it, i'm not sure you can specify pre-processor directives on a swift package you import. And if you can i'm not sure how. 
2. You don't use #debug in any of the places this property is called.

2024-10-21 17:02 UTC, scottasoutherland approved these changes

2024-10-21 17:06 UTC, merged